React & Redux group project - Space Travelers' Hub
benshidanny11/space-travelers pull request #30
Opened 2022-06-16 21:36 UTC by benshidanny11

### In this project  we : 
:heavy_check_mark: Implemented basic project setup (React, Redux, Folder structure)
:heavy_check_mark: Fetched data from APIs and updated Redux store
:heavy_check_mark: Populated data from redux store to react components
:heavy_check_mark: Wrote actions and reducers for booking rockets and joining missions
:heavy_check_mark: Wrote actions and reducers for canceling rockets/dragons and leaving missions
:heavy_check_mark: Implemented conditional component rendering
:heavy_check_mark: Implemented my profile section (Displayed reserved rockets and missions)
:heavy_check_mark: Wrote actions and reducers for canceling rockets/dragons and leaving missions
:heavy_check_mark: Wrote actions and reducers for canceling rockets/dragons and leaving missions
:heavy_check_mark: Implemented unit tests

2022-06-16 23:17 UTC, keneogu requested changes
Hi @benshidanny11 & @KanoCode, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Good commit history
- Good PR description
- Nice design

There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media4.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif)

## Required Changes ♻️

- [ ] Please, add how to run the tests on the readme file.

_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] In the Profile Section, add the "Cancel reservation" and "Leave Mission" buttons to the lists here. Clicking them should dispatch the actions you have already used in the main Rockets and Missions sections. 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 23:17 UTC, keneogu commented on src/components/App.js
> +        <Head />
- [ ] <NavLink  /> should be used for navbar...Let's make this look more professional change this to <NavLink /> and go to the pages folder and rename NavBar.js to follow a great naming convention.

2022-06-17 05:45 UTC, benshidanny11 commented on src/components/App.js
> +        <Head />
Hello @keneogu,
Thanks for providing us with feedback, we are going to implement them.

2022-06-17 06:32 UTC, mateo951 approved these changes
### Hi Team, 

Well done making the changes requested by the previous reviewer 🔥
Your project is complete!  There is nothing else to say other than... it's time to merge it ✔ 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-17 06:32 UTC, mateo951 commented on src/components/App.js
> +        <NavBar />
Addressed 🙌

2022-06-17 11:09 UTC, merged